import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
const inter = Inter({ subsets: ["latin"] });
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import SideBra from "../sideBar/page";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-[50px] w-[100%]">
          <div className="w-[18%] h-[100vh] ">
            <SideBra />
          </div>
          <div className="w-[82%]">
            <AppRouterCacheProvider>
              {children}
            </AppRouterCacheProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
